kind: Pod
apiVersion: v1
metadata:
  name: push-test
  namespace: demo-microservice-cicd
  annotations:
    openshift.io/scc: nonroot-build
    seccomp.security.alpha.kubernetes.io/pod: unconfined
spec:
  restartPolicy: Never
  serviceAccountName: operate-workflow-sa
  securityContext:
    seccompProfile:
      type: Unconfined
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 4Gi
        requests:
          cpu: 250m
          memory: 512Mi
      stdin: true
      terminationMessagePath: /dev/termination-log
      stdinOnce: true
      name: main
      command:
        - /bin/sh
      securityContext:
        capabilities:
          add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETFCAP
            - SETGID
            - SETUID
          drop:
            - MKNOD
        runAsUser: 1000
        runAsGroup: 0
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      imagePullPolicy: Always
      volumeMounts:
        - name: workspace
          mountPath: /mnt/out/
      terminationMessagePolicy: File
      tty: true
      image: 'ghcr.io/gepaplexx/buildah:latest'
  serviceAccount: operate-workflow-sa
  volumes:
    - name: var-run-argo
      emptyDir: { }
    - name: tmp-dir-argo
      emptyDir: { }
    - name: tmp
      emptyDir: { }
    - name: workspace
      emptyDir: { }
  dnsPolicy: ClusterFirst
